bazel_dep(name = "aspect_rules_js", version = "0.0.0", dev_dependency = True)
local_path_override(
    module_name = "aspect_rules_js",
    path = "../..",
)

bazel_dep(name = "bazel_skylib", version = "1.5.0", dev_dependency = True)

yarn_lock = use_extension(
    "@aspect_rules_js//npm:extensions.bzl",
    "yarn_lock",
    dev_dependency = True,
)
yarn_lock.generate(
    name = "generated-yarn-graph",
    binary_data = ["//:binary_fixture.dat"],
    data = [
        "//:.yarn/patches/semver-npm-7.6.3-57e82c14d5.patch",
        "//:.yarnrc.yml",
        "//:package.json",
        "//packages/consumer-seven:package.json",
        "//packages/consumer-six:package.json",
        "//packages/peer-reader:package.json",
    ],
    expected_graph_sha256 = "129d23f372f07f21175fea9e53c210e880554aebc437d61880618f1e81d32099",
    quiet = False,
    supported_cpu = ["current"],
    supported_libc = ["current"],
    supported_os = ["current"],
    yarn_lock = "//:yarn.lock",
)
yarn_lock.generate(
    name = "generated-yarn-classic-graph",
    binary_data = ["//:binary_fixture.dat"],
    data = [
        "//classic:.yarnrc.yml",
        "//classic:package.json",
    ],
    expected_graph_sha256 = "d7f8c2a5f324fc7a1a3199c76246bd91f57afd1a6a9114233f2afee4b8fe039f",
    quiet = False,
    yarn_lock = "//classic:yarn.lock",
)
use_repo(
    yarn_lock,
    "generated-yarn-classic-graph",
    "generated-yarn-graph",
)

npm = use_extension(
    "@aspect_rules_js//npm:extensions.bzl",
    "npm",
    dev_dependency = True,
)
npm.npm_translate_lock(
    name = "npm",
    quiet = False,
    verify_node_modules_ignored = "//:.bazelignore",
    yarn_graph = "@generated-yarn-graph//:yarn_graph.json",
)
npm.npm_translate_lock(
    name = "npm_classic",
    quiet = False,
    verify_node_modules_ignored = "//:.bazelignore",
    yarn_graph = "@generated-yarn-classic-graph//classic:yarn_graph.json",
)
use_repo(npm, "npm", "npm_classic")
