"""Repository rule materializing a Yarn PnP zero-install project for Bazel.

Generates pnp_preload.cjs into the repo for native sandbox remapping.
"""

load(":pnp_data.bzl", "pnp_data")

_DEFS_BZL_TMPL = '''\
"""@generated by pnp_repository; do not edit."""

load("@aspect_rules_js//js:defs.bzl", _js_binary = "js_binary", _js_library = "js_library", _js_test = "js_test")

PNP_PACKAGES = json.decode("""{packages_json}""")
PNP_RUNTIME_SRCS = {runtime_srcs}
_PNP_PRELOAD = "@pnp//:pnp_preload.cjs"
_EXTRA_NODE_OPTIONS = {extra_node_options}

def pnp_files(name, **kwargs):
    native.filegroup(name = name, srcs = PNP_RUNTIME_SRCS, **kwargs)

def _pnp_wrap(kwargs):
    kwargs["data"] = kwargs.get("data", []) + PNP_RUNTIME_SRCS + [_PNP_PRELOAD]
    kwargs["node_options"] = kwargs.get("node_options", []) + [
        "--require=./external/__REPO_CANONICAL__/pnp_preload.cjs",
    ] + _EXTRA_NODE_OPTIONS
    kwargs["no_copy_to_bin"] = kwargs.get("no_copy_to_bin", []) + PNP_RUNTIME_SRCS + [_PNP_PRELOAD]
    env = dict(kwargs.get("env", {{}}))
    env.setdefault("JS_BINARY__PATCH_NODE_FS", "0")
    env.setdefault("PNP_WORKSPACE_ROOT", "{root_package_path}")
    kwargs["env"] = env
    return kwargs

def pnp_js_binary(name, **kwargs):
    _js_binary(name = name, **_pnp_wrap(kwargs))

def pnp_js_test(name, **kwargs):
    _js_test(name = name, **_pnp_wrap(kwargs))

def pnp_verify_test(name, **kwargs):
    _js_test(name = name, entry_point = "@aspect_rules_js//npm/private/pnp:pnp_verify", data = PNP_RUNTIME_SRCS, env = {{"PNP_ROOT": "{root_package_path}"}}, **kwargs)

def npm_link_all_packages(name = "node_modules", **kwargs):
    native.filegroup(name = name, srcs = PNP_RUNTIME_SRCS, **kwargs)
    seen = {{}}
    all_locators = list(PNP_PACKAGES.keys())
    for pkg_info in PNP_PACKAGES.values():
        for dep_locator in pkg_info.get("dependencies", []):
            all_locators.append(dep_locator)
    for locator in all_locators:
        pkg_name = None
        if locator.startswith("@"):
            slash_idx = locator.find("/")
            if slash_idx < 0: continue
            at_idx = locator[slash_idx + 1:].find("@")
            if at_idx < 0: continue
            pkg_name = locator[:slash_idx + 1 + at_idx]
        else:
            at_idx = locator.find("@")
            if at_idx <= 0: continue
            pkg_name = locator[:at_idx]
        if pkg_name in seen: continue
        seen[pkg_name] = True
        if ":" in pkg_name or "%" in pkg_name: continue
        _js_library(name = "node_modules/" + pkg_name, srcs = [], visibility = ["//visibility:public"])
'''

_BUILD_TMPL = '''\
"""@generated by pnp_repository; do not edit."""
exports_files(["defs.bzl", "pnp_preload.cjs"])
'''

def _pnp_repository_impl(rctx):
    lock_content = rctx.read(rctx.attr.yarn_lock)
    pnp_json = rctx.read(rctx.attr.pnp_data)

    parsed = pnp_data.parse(pnp_json)
    validated = pnp_data.validate(parsed, lock_content)
    if validated.errors:
        # buildifier: disable=print
        print("pnp_repository {}: validation notes (non-fatal):\n  {}".format(
            rctx.name,
            "\n  ".join(validated.errors[:5] + (["... and {} more".format(len(validated.errors) - 5)] if len(validated.errors) > 5 else [])),
        ))

    data_label = rctx.attr.pnp_data
    root_package = "@@{}//{}".format(data_label.workspace_name, data_label.package)

    runtime_srcs = [
        str(rctx.attr.pnp_cjs),
        str(rctx.attr.pnp_data),
        str(rctx.attr.yarn_lock),
    ] + [
        "{}:.yarn/cache/{}".format(root_package, zip_name)
        for zip_name in validated.cache_zips
    ] + [str(label) for label in rctx.attr.extra_data]

    pnp_cjs_rootpath = "/".join([p for p in [data_label.package, rctx.attr.pnp_cjs.name] if p])

    # Copy the preload template into this repo
    preload_content = rctx.read(Label("@aspect_rules_js//npm/private/pnp:pnp_preload.cjs.tmpl"))
    rctx.file("pnp_preload.cjs", preload_content)

    # Generate defs.bzl using .format(), then replace the repo name placeholder
    defs_content = _DEFS_BZL_TMPL.format(
        packages_json = json.encode_indent(validated.packages, indent = "  "),
        runtime_srcs = json.encode_indent(runtime_srcs, indent = "  "),
        extra_node_options = json.encode(rctx.attr.extra_node_options),
        pnp_cjs_rootpath = pnp_cjs_rootpath,
        root_package_path = data_label.package if data_label.package else ".",
    )
    # rctx.name is the full canonical name (e.g., "aspect_rules_js~~pnp~pnp")
    defs_content = defs_content.replace("__REPO_CANONICAL__", rctx.name)
    rctx.file("defs.bzl", defs_content)
    rctx.file("BUILD.bazel", _BUILD_TMPL)

pnp_repository = repository_rule(
    implementation = _pnp_repository_impl,
    attrs = {
        "pnp_cjs": attr.label(mandatory = True, allow_single_file = True),
        "pnp_data": attr.label(mandatory = True, allow_single_file = True),
        "yarn_lock": attr.label(mandatory = True, allow_single_file = True),
        "extra_data": attr.label_list(default = []),
        "extra_node_options": attr.string_list(default = []),
    },
)
