"""Module extension for consuming Yarn PnP zero-install projects.

Experimental. Usage in MODULE.bazel:

    pnp = use_extension("@aspect_rules_js//npm/private/pnp:pnp_extension.bzl", "pnp")
    pnp.install(
        name = "pnp",
        pnp_cjs = "//:.pnp.cjs",
        pnp_data = "//:.pnp.data.json",
        yarn_lock = "//:yarn.lock",
    )
    use_repo(pnp, "pnp")

rules_js never runs Yarn: the three files above are generated by the user
with `yarn install` (with `pnpEnableInlining: false`) and checked in together
with the offline cache under .yarn/cache, as in any Yarn zero-install setup.
"""

load(":pnp_repository.bzl", "pnp_repository")

_install = tag_class(
    attrs = {
        "name": attr.string(
            doc = "Name of the generated repository.",
            default = "pnp",
        ),
        "pnp_cjs": attr.label(
            doc = "The checked-in .pnp.cjs resolver.",
            mandatory = True,
        ),
        "pnp_data": attr.label(
            doc = "The checked-in .pnp.data.json file.",
            mandatory = True,
        ),
        "yarn_lock": attr.label(
            doc = "The checked-in Yarn Berry yarn.lock file.",
            mandatory = True,
        ),
        "extra_data": attr.label_list(
            doc = "Additional data files to include in PNP_RUNTIME_SRCS (e.g., ESM loaders, propagation scripts).",
            default = [],
        ),
        "extra_node_options": attr.string_list(
            doc = "Additional --require or other node options to add (e.g., ['--require=./path/to/preload.cjs']).",
            default = [],
        ),
    },
    doc = "Declares one Yarn PnP zero-install project to consume.",
)

def _pnp_impl(mctx):
    for mod in mctx.modules:
        for install in mod.tags.install:
            pnp_repository(
                name = install.name,
                pnp_cjs = install.pnp_cjs,
                pnp_data = install.pnp_data,
                yarn_lock = install.yarn_lock,
                extra_data = install.extra_data,
                extra_node_options = install.extra_node_options,
            )

pnp = module_extension(
    implementation = _pnp_impl,
    tag_classes = {
        "install": _install,
    },
    doc = "Consumes checked-in Yarn PnP zero-install projects without running Yarn.",
)
