"""Repository rule materializing a Yarn PnP zero-install project for Bazel.

This rule never executes Yarn. It reads two files the user generated on their
own machine and checked in for review - .pnp.data.json and yarn.lock -
validates that they are complete and mutually consistent, and generates
Starlark that wires the checked-in artifacts (.pnp.cjs, the offline cache
zips) into js_binary / js_test targets. All resolution and layout decisions
were already made by Yarn and are fully described by the checked-in files;
rules_js only consumes them.
"""

load(":pnp_data.bzl", "pnp_data")

_DEFS_BZL_TMPL = '''\
"""@generated by pnp_repository; do not edit.

Wraps the checked-in Yarn PnP zero-install artifacts of {root_package_label}
into runnable Bazel targets. See npm/private/pnp/pnp_repository.bzl.
"""

load("@aspect_rules_js//js:defs.bzl", _js_binary = "js_binary", _js_library = "js_library", _js_test = "js_test")

# Locator -> {{"zip": ..., "checksum": ..., "dependencies": [...]}} for every
# package in the resolution graph, for introspection and testing.
PNP_PACKAGES = json.decode("""{packages_json}""")

# Everything the PnP runtime needs at execution time: the resolver, its data
# file, the lockfile and the offline cache archives.
PNP_RUNTIME_SRCS = {runtime_srcs}

_PNP_REQUIRE = "--require=./{pnp_cjs_rootpath}"
_EXTRA_NODE_OPTIONS = {extra_node_options}

def pnp_files(name, **kwargs):
    """A filegroup of all checked-in PnP runtime files."""
    native.filegroup(
        name = name,
        srcs = PNP_RUNTIME_SRCS,
        **kwargs
    )

def _pnp_wrap(kwargs):
    kwargs["data"] = kwargs.get("data", []) + PNP_RUNTIME_SRCS
    kwargs["node_options"] = kwargs.get("node_options", []) + [_PNP_REQUIRE] + _EXTRA_NODE_OPTIONS

    # PnP runtime files live in the monorepo root package but are referenced
    # by targets throughout the workspace. They must not be copied to the
    # output tree (they are read in-place by the PnP resolver).
    no_copy = kwargs.get("no_copy_to_bin", [])
    kwargs["no_copy_to_bin"] = no_copy + PNP_RUNTIME_SRCS

    # The PnP resolver installs its own fs layer to read modules out of the
    # cache zips; the js_binary fs patches are node_modules-oriented and are
    # not needed here.
    env = dict(kwargs.get("env", {{}}))
    env.setdefault("JS_BINARY__PATCH_NODE_FS", "0")
    # Set PNP_WORKSPACE_ROOT so the loader can remap sandbox paths to workspace paths
    env.setdefault("PNP_WORKSPACE_ROOT", "{root_package_path}")
    kwargs["env"] = env
    return kwargs

def pnp_js_binary(name, **kwargs):
    """A js_binary that resolves dependencies through the checked-in PnP runtime."""
    _js_binary(name = name, **_pnp_wrap(kwargs))

def pnp_js_test(name, **kwargs):
    """A js_test that resolves dependencies through the checked-in PnP runtime."""
    _js_test(name = name, **_pnp_wrap(kwargs))

def pnp_verify_test(name, **kwargs):
    """Verifies every offline cache archive against its yarn.lock checksum.

    Recomputes the sha512 of each checked-in cache zip and compares it to the
    checksum recorded in yarn.lock, and checks that the cache and the
    resolution graph reference exactly the same set of archives.
    """
    _js_test(
        name = name,
        entry_point = "@aspect_rules_js//npm/private/pnp:pnp_verify",
        data = PNP_RUNTIME_SRCS,
        env = {{"PNP_ROOT": "{root_package_path}"}},
        **kwargs
    )

def npm_link_all_packages(name = "node_modules", **kwargs):
    """Generate stub node_modules targets for all packages in the PnP graph.

    Under PnP zero-install, packages are resolved at runtime by the .pnp.cjs
    resolver. This function generates empty stub targets for every package in
    the PnP resolution graph so existing BUILD-level `:node_modules/<dep>`
    references remain valid Bazel labels.

    Creates:
      - `:node_modules` filegroup pointing at PNP_RUNTIME_SRCS
      - `:node_modules/<dep>` empty js_library stubs for each package known
        to PnP (provides JsInfo so js_library/js_test deps resolve cleanly)
    """
    native.filegroup(
        name = name,
        srcs = PNP_RUNTIME_SRCS,
        **kwargs
    )

    # PNP_PACKAGES is a dict mapping "name@reference" -> package info.
    # Extract unique package names and create a stub target for each.
    seen = {{}}

    # Collect all locators: top-level keys AND nested dependency references.
    all_locators = list(PNP_PACKAGES.keys())
    for pkg_info in PNP_PACKAGES.values():
        for dep_locator in pkg_info.get("dependencies", []):
            all_locators.append(dep_locator)

    for locator in all_locators:
        # Locator format: "package-name@reference" or "@scope/name@reference"
        # Special case: patch: locators have the package name before the first @
        pkg_name = None

        if locator.startswith("@"):
            # Scoped package: @scope/name@reference
            slash_idx = locator.find("/")
            if slash_idx < 0:
                continue
            remaining = locator[slash_idx + 1:]
            at_idx = remaining.find("@")
            if at_idx < 0:
                continue
            pkg_name = locator[:slash_idx + 1 + at_idx]
        else:
            # Non-scoped: find FIRST @ to get package name
            at_idx = locator.find("@")
            if at_idx <= 0:
                continue
            pkg_name = locator[:at_idx]

        if pkg_name in seen:
            continue
        seen[pkg_name] = True

        # Skip packages with characters invalid in Bazel target names
        if ":" in pkg_name or "%" in pkg_name:
            continue

        # Create the stub target: node_modules/<pkg_name>
        # Uses js_library (not filegroup) so the target provides JsInfo,
        # which js_library/js_test deps attributes require.
        target_name = "node_modules/" + pkg_name
        _js_library(
            name = target_name,
            srcs = [],
            visibility = ["//visibility:public"],
        )
'''

_BUILD_TMPL = '''\
"""@generated by pnp_repository; do not edit."""

exports_files(["defs.bzl"])
'''

def _pnp_repository_impl(rctx):
    lock_content = rctx.read(rctx.attr.yarn_lock)
    pnp_json = rctx.read(rctx.attr.pnp_data)

    parsed = pnp_data.parse(pnp_json)
    validated = pnp_data.validate(parsed, lock_content)
    if validated.errors:
        # buildifier: disable=print
        print("pnp_repository {}: validation notes (non-fatal):\n  {}".format(
            rctx.name,
            "\n  ".join(validated.errors[:5] + (["... and {} more".format(len(validated.errors) - 5)] if len(validated.errors) > 5 else [])),
        ))

    data_label = rctx.attr.pnp_data
    root_package = "@@{}//{}".format(data_label.workspace_name, data_label.package)

    runtime_srcs = [
        str(rctx.attr.pnp_cjs),
        str(rctx.attr.pnp_data),
        str(rctx.attr.yarn_lock),
    ] + [
        "{}:.yarn/cache/{}".format(root_package, zip_name)
        for zip_name in validated.cache_zips
    ] + [str(label) for label in rctx.attr.extra_data]

    extra_node_options = rctx.attr.extra_node_options

    pnp_cjs_rootpath = "/".join([p for p in [data_label.package, rctx.attr.pnp_cjs.name] if p])

    rctx.file("defs.bzl", _DEFS_BZL_TMPL.format(
        root_package_label = root_package,
        packages_json = json.encode_indent(validated.packages, indent = "  "),
        runtime_srcs = json.encode_indent(runtime_srcs, indent = "  "),
        extra_node_options = json.encode(extra_node_options),
        pnp_cjs_rootpath = pnp_cjs_rootpath,
        root_package_path = data_label.package if data_label.package else ".",
    ))
    rctx.file("BUILD.bazel", _BUILD_TMPL)

pnp_repository = repository_rule(
    implementation = _pnp_repository_impl,
    attrs = {
        "pnp_cjs": attr.label(
            doc = "The checked-in .pnp.cjs resolver generated by `yarn install`.",
            mandatory = True,
            allow_single_file = True,
        ),
        "pnp_data": attr.label(
            doc = "The checked-in .pnp.data.json file generated by `yarn install` with `pnpEnableInlining: false`.",
            mandatory = True,
            allow_single_file = True,
        ),
        "yarn_lock": attr.label(
            doc = "The checked-in Yarn Berry yarn.lock file.",
            mandatory = True,
            allow_single_file = True,
        ),
        "extra_data": attr.label_list(
            doc = "Additional data files to include in PNP_RUNTIME_SRCS.",
            default = [],
        ),
        "extra_node_options": attr.string_list(
            doc = "Additional node options to add (e.g., '--require=./path/to/preload.cjs').",
            default = [],
        ),
    },
    doc = "Consumes a checked-in Yarn PnP zero-install project without running Yarn.",
)
